version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:8@sha256:4739aa55dcaafafacfbba3005ad30b90eb16a38e6e48c8c13ef7e3893babac24'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run: npm test
      - run:
          name: Upload code coverage to Codecov
          command: 'bash <(curl -s https://codecov.io/bash)'
